name: Website Checks
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/website.yml
      - website/docs/**

env:
  GO_VERSION: "1.14"
  GO111MODULE: on

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.markdownlinkcheck.json'
          folder-path: 'website/docs'
          file-extension: '.markdown'
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: avto-dev/markdown-lint@v1.3.0
        with:
          config: '.markdownlint.yml'
          args: 'website/docs'
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v2
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - run: go install github.com/client9/misspell/cmd/misspell
      - run: misspell -error -source text website/
  terrafmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v2
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - run: go install github.com/katbyte/terrafmt
      - run: terrafmt diff ./website --check --pattern '*.markdown' --quiet
